name = "Hugo Winston"
license = "MIT"
licenselink = "https://github.com/zerostaticthemes/hugo-winston/blob/master/LICENSE"
description = "Hugo Winston is a bold minimal blogging theme"
homepage = "https://github.com/jugglerx/hugo-hero-theme"
tags = ["blog","minimal","company","bootstrap","zerostatic"]
features = ["blog"]
min_version = 0.80

[author]
  name = "Robert Austin"
  homepage = "https://www.zerostatic.io"