baseURL = "www.example.com"
languageCode = "en-us"
title = "Hugo Winston"
themesDir = "../.."
theme = "hugo-winston"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
paginate = 3

[params]
  google_analytics_id = ""
  showAuthorOnHomepage = true
  showPostsOnHomepage = false
  showAuthorOnPosts = true
  showSummaryDescription = true
  addFrame = true
  addDot = true

[permalinks]
  posts = "blog/:year/:month/:title/"
  pages = ":slug/"